### ISSUE TITLE
Cache seems to be a singleton [resolved]

### ISSUE THREAD

**Issue by vdobler** [OrlovEvgeny/go-mcache#13]
Try this:

	a, b := mcache.New(), mcache.New()
	a.Set("foo", 123, time.Second)
	val, ok := b.Get("foo")
	fmt.Println(val, ok)

Which will produce "123 ok".
It seems you cannot have multiple caches. This should either be documented clearly or fixed.

**Comment by OrlovEvgeny** [comment]
Yes you right. I think that it need does fix

Thanks.
